In [3]:
import numpy as np

# Load .npy file
my_array = np.load('data\processed\Cell_Flask_160mL_31ml_2404_5016\Input_DepthMap.npy')

# Print loaded array
print(my_array)

# print average depth
print("Average depth: ", np.average(my_array))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Average depth:  273.4457096354167


In [7]:
# Load .npy file
my_array = np.load('data\processed\Cell_Flask_160mL_32ml_0905_1325\Input_ContentDepth_segmented.npy')

# Print loaded array
print(my_array)

# print average depth
print("Average depth: ", np.average(my_array))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Average depth:  0.10535


In [10]:
# Load .npy file
my_array = np.load('data\processed\Pyrex_100mL_18ml_0905_1643\Input_ContentDepth_segmented.npy')

# Print loaded array
print(my_array)

# print average depth
print("Average depth: ", np.average(my_array))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Average depth:  0.0353


In [ ]:
C:\Users\apo_n\Documents\GitHub\thesis\volume_estimation\

In [11]:
# Load .npy file
my_array = np.load('data\processed\Gibco_500mL_352ml_0905_4411\Input_ContentMaskClean.npy')

# Print loaded array
print(my_array)

# print average depth
print("Average depth: ", np.average(my_array))

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Average depth:  0.05373372395833333


In [12]:
# Load .npy file
my_array = np.load('data\processed\Tube_50mL_48ml_2404_5728\Input_ContentMaskClean.npy')

# Print loaded array
print(my_array)

# print average depth
print("Average depth: ", np.average(my_array))

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Average depth:  0.08233072916666667


In [13]:
# Load .npy file
my_array = np.load('data\processed\Tube_50mL_48ml_2404_5725\Input_ContentMaskClean.npy')

# Print loaded array
print(my_array)

# print average depth
print("Average depth: ", np.average(my_array))

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Average depth:  0.038125
